### ISSUE TITLE
strange social icon display on site

### ISSUE THREAD

**Issue by Jasonwi** [jakewies/hugo-theme-codex#64] opened 2020-07-04 16:06 UTC
I deploy the static website successfully at local but the social icon not appear at the about page
i check your github pages have same situation
hugo env
```
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.13.8"

```
![Snipaste_2020-07-04_23-51-03](https://user-images.githubusercontent.com/59698185/86516429-0d203900-be53-11ea-9ca9-fabd7ee6c518.png)

![demo](https://github.com/jakewies/hugo-theme-codex/raw/master/images/screenshot.png)

**Comment by jakewies** [comment] 2020-07-04 16:19
Hey @Jasonwi, have you made any changes to your `config.toml`?

**Comment by jakewies** [comment] 2020-07-04 17:00
I notice that the demo site isn't rendering with icons either. But when I follow the README instructions the site will render locally with twitter and github icons. @kentnek any thoughts? Still debugging.

**Comment by kentnek** [comment] 2020-07-04 17:45
![image](https://user-images.githubusercontent.com/7024160/86518111-203a0580-be61-11ea-9a0c-a100c3cf6970.png)
hmm looks like the icons don't exist on the server that hosts the demo. Is it possible to see the demo's file contents?

**Comment by kentnek** [comment] 2020-07-04 17:51
I think [this is the culprit](https://github.com/gohugoio/hugoThemes#common-permalink-issues):
> If using inline styles, these need to use absolute URLs, for the linked assets to be served properly, e.g. <div style="background: url('{{ "images/background.jpg" | absURL }}')">
We probably just need to add the `absURL` pipe for the demo site to work.

For @Jasonwi, it could be a different problem as locally it works fine for me. Could you share your `config.toml` file?

**Comment by Jasonwi** [comment] 2020-07-05 00:00
@kentnek When i first depoly locally the icon display normal but i forgot what changes were made cause the icon disappear

`config.toml` 
```
# Override these settings with your own
languageCode = "en-us"

copyright = "© {year}"

theme = "codex" 

# Optional params
[params]
  dateFormat = "Jan 2 2006"
  twitter = "https://twitter.com/<your handle>"
  github = "https://github.com/<your handle>"  
  # "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconTitles = ["Twitter", "GitHub"]

[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

```

**Comment by kentnek** [comment] 2020-07-05 14:02
@Jasonwi your config looks fine to me. If you use Chrome/Firefox, could you open the Inspect/Inspector and see what the error message is?

**Comment by Jasonwi** [comment] 2020-07-06 03:25
@kentnek on my edge i catch the icon url /images/social/twitter.svg get `https://themes.gohugo.io//theme/hugo-theme-codex/images/social/twitter.svg` normal but not show on page(local and codex pages)
 
![Snipaste_2020-07-06_11-00-45](https://user-images.githubusercontent.com/59698185/86552609-15739380-bf7b-11ea-8b27-a7b09f54deb7.png)

![Snipaste_2020-07-06_10-59-21](https://user-images.githubusercontent.com/59698185/86552657-3b993380-bf7b-11ea-8887-a6e214ef66f1.png)

**Comment by kentnek** [comment] 2020-07-06 03:45
@Jasonwi can you show the Console with the error log instead?

**Comment by Jasonwi** [comment] 2020-07-06 04:24
@kentnek it's shows nothing 
![my local site](https://o2-1258123310.cos.ap-beijing.myqcloud.com/images20200706122245.png)

**Comment by kentnek** [comment] 2020-07-06 05:56
on the demo the icons are not showing due to "https://themes.gohugo.io/theme/hugo-theme-codex" due to a different bug. And it should have shown the error log like this:

![image](https://user-images.githubusercontent.com/7024160/86560185-53c77d80-bf90-11ea-8079-e35672b8295e.png)

The bug is fixed and whenever Hugo Themes rebuilds our code, it'll be reflected on the demo site.

However, for your website it's kinda strange. Can you `git submodule update` your theme, clear your local site's cache and try again?

**Comment by Jasonwi** [comment] 2020-07-06 06:34
@kentnek many thx! the strange issue cause the Adguard default rule catch the social infomation [Social media filter](https://kb.adguard.com/en/general/adguard-ad-filters#social-media-filter)
I really didn't think it would cause this issue until i install a new browser 😂

**Comment by kentnek** [comment] 2020-07-06 06:39
Oh this is actually interesting! It never came to me that ad blocking extensions might complain because we have "social" in our asset paths. What are your thoughts on this? @jakewies

**Comment by jakewies** [comment] 2020-07-06 18:06
Yoinks. A few weeks ago we had [an issue arise](https://github.com/jakewies/hugo-theme-codex/issues/47) over a similar issue. It resulted in https://github.com/jakewies/hugo-theme-codex/pull/48 which renamed `/static/icons` (old) to `/static/images/social` (current). So now we have run into another one of these naming issues 😆 

Ok, so it looks like the quickest solution would be to rename the asset path again, yes?

If that will solve this issue, my suggestion would be to rename the asset path from `/static/images/social` to `/static/svg`. Then we can move all icons, social or otherwise, to this directory. What do you think?

**Comment by kentnek** [comment] 2020-07-06 18:27
`static/svg` sounds good to me. I can't think of a situation where that would become a problem hahaha

**Comment by jakewies** [comment] 2020-07-08 00:54
Same lol I'll open a PR for this

**Comment by siberianTrousers** [comment] 2020-07-13 21:47
Just to follow up on this, are you able to help me figure out why I cannot get the social icon to display as desired after updating the filepath to static/svg?

added quickstart/static/svg/reddit.svg:


![image](https://user-images.githubusercontent.com/68250261/87356882-e2a83d00-c530-11ea-8673-046e2433897c.png)



```
# config.toml
...
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  # twitter = "https://twitter.com/<your handle>"
  # github = "https://github.com/<your handle>"
  # email = "mailto:<your email>"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  reddit = "https://www.reddit.com/r/cptsd_bookclub"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconTitles = ["Reddit"]
...

```
the site: 
![image](https://user-images.githubusercontent.com/68250261/87356776-ac6abd80-c530-11ea-8ffd-9ab45d22e8de.png)

**Comment by Jasonwi** [comment] 2020-07-14 00:30
@siberianTrousers try to modify theme template file `themes/codex/layouts/partials/social-icons.html`
modified
```
{{ $currentPage := . }}
{{ $icons := .Site.Params.iconOrder | default (slice "Twitter" "GitHub" "Email" "Facebook" "GitLab" "Instagram" "LinkedIn" "YouTube" "Reddit") }}

<div class="social-icons">
  {{ range $icons }}
    {{ $icon := anchorize . }} 
    {{ if isset $currentPage.Site.Params $icon }}
      <a class="social-icons__icon" title="{{ . }}"
         style="background-image: url(/images/social/{{ $icon }}.svg)" 
         href="{{ index $currentPage.Site.Params $icon }}"
         target="_blank" rel="noopener">
      </a>
    {{ end }}
  {{ end }}   
</div>

```
also add svg file to this path `themes/codex/static/images/social`
show that
![image](https://user-images.githubusercontent.com/59698185/87366511-6f8fdc80-c5ab-11ea-9de8-437b281d7e06.png)

**Comment by jakewies** [comment] 2020-07-14 02:05
Hey @siberianTrousers , so the change hasn't been made yet. I'm working on it right now. I'll ping here when the change has been made.

**Comment by jakewies** [comment] 2020-07-14 02:37
Added https://github.com/jakewies/hugo-theme-codex/pull/76 to fix this. When it's merged everything should be working as intended as long as you place the icon at `static/svg`.

**Comment by siberianTrousers** [comment] 2020-07-14 04:39
Thanks! Just a quick question, its my first time updating a hugo theme and i'm not sure how to go about doing it? I didn't fork your repo but installed through hugo library on brew. i double checked readme.md but didn't see anything on that (unless i missed it).

**Comment by jakewies** [comment] 2020-07-14 13:15
> i double checked readme.md but didn't see anything on that (unless i missed it).

In the `README` there is a [getting started section](https://github.com/jakewies/hugo-theme-codex#getting-started) that describes how to install the theme and use it. In general we do not recommend installing the theme through homebrew. We recommend installing the theme using the official methods described in the [`gohugo` docs](https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme):

```
git submodule add https://github.com/jakewies/hugo-theme-codex.git themes/hugo-theme-codex
```

**Comment by siberianTrousers** [comment] 2020-07-14 13:17
Sorry, yes I meant to say I installed Hugo via home brew but Followed your instructions to the tee to install theme.

With regards to newly committed vers, I can just repeat the steps to get the update? -- 
Statement of Confidentiality: 

The contents of this e-mail message and any attachments are        confidential and are intended solely for addressee. The        information may also be legally privileged. This transmission is        sent in trust, for the sole purpose of delivery to the intended        recipient. If you have received this transmission in error, any        use, reproduction or dissemination of this transmission is        strictly prohibited. If you are not the intended recipient, immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.



Jul 14, 2020, 09:15 by notifications@github.com:

**Comment by jakewies** [comment] 2020-07-14 13:34
We haven't really documented how to get theme updates. You have a few options available to you.

1. Follow the instructions in the [git docs](https://git-scm.com/book/en/v2/Git-Tools-Submodules). If you scroll down the page you'll find a section called "Pulling in Upstream Changes from the Submodule Remote". If you follow these instructions you should be able to merge changes from the remote repo (hosted here on github).

2. If you're unsure of how this works, you could always remove the current theme and re-add it using `git submodule add`.

I don't often work with git submodules but I would say number 1 is your best route.

**Comment by siberianTrousers** [comment] 2020-07-14 13:34
Sorry, yes I meant to say I installed Hugo via home brew but Followed your instructions to the tee to install theme.

Just to follow up, i'm trying to reinitiate the hugo project, and im having trouble reinstalling your theme. 

```
$ git submodule add https://github.com/jakewies/hugo-theme-codex.git themes/hugo-theme-codex
'quickstart/themes/hugo-theme-codex' already exists in the index
$ git ls-files --stage
...
160000 2e2f558a819a0b82499b613bb5a7e1e3462e9576 0	themes/hugo-theme-codex
$ git rm --cached themes/hugo-theme-codex
$ rm 'quickstart/themes/hugo-theme-codex'
$ git submodule add https://github.com/jakewies/hugo-theme-codex.git themes/hugo-theme-codex
A git directory for 'quickstart/themes/hugo-theme-codex' is found locally with remote(s):
  origin	https://github.com/jakewies/hugo-theme-codex.git
If you want to reuse this local git directory instead of cloning again from
  https://github.com/jakewies/hugo-theme-codex.git
use the '--force' option. If the local git directory is not the correct repo
or you are unsure what this means choose another name with the '--name' option.
$ git submodule add --force https://github.com/jakewies/hugo-theme-codex.git themes/hugo-theme-codex
Reactivating local git directory for submodule 'quickstart/themes/hugo-theme-codex'.
```

**Comment by jakewies** [comment] 2020-07-14 14:03
Ok, it looks like you opted for # 2, which is probably not the best way to do that. I'm going to edit my comment and remove that option.

Since I've never done this before, I'm not sure what the best answer for you is. I would try to stick to the git documentation as closely as possible. The `--force` option does nothing for you other than reuse the existing directory you added in step 1. So you won't be getting any upstream changes.

Since it seems you are using `quickstart` as a tutorial perhaps? Maybe it would be best to start fresh. If you can. In that case, any time you want to update the submodule you can `cd` into the theme directory:

```
cd themes/hugo-theme-codex
```

And run:

```
git fetch
git merge origin/master
```

Of course this isn't always a safe option, given the fact that we can introduce a change at any time that could potentially break your site. We do our best to document changes and update versions when necessary.

The steps you've taken above seem fine for your current situation. Nothing has changed based on the results of your commands. If you want to wait until #76 is resolved we can walk through updating your theme together.

**Comment by jakewies** [comment] 2020-07-14 14:13
Not sure why the issue closed, I guess if you use the "fixes <issue_number>" syntax in a PR, GitHub will auto-close the issue when the PR is merged.

Anyway, the changes have been introduced into the repo. @siberianTrousers , [the steps you outlined in your original comment](https://github.com/jakewies/hugo-theme-codex/issues/64#issuecomment-657810187) should now work.

The obstacle you'll need to overcome at this point is updating the theme that you installed via:

```
git submodule add ...
```

If you can simply trash the `quickstart` project and re-start from scratch you will receive the changes immediately. Otherwise we can work on how to get your theme updated. Just ping me if you have questions.

**Comment by kentnek** [comment] 2020-07-14 15:33
By the way @siberianTrousers I just wrote a [blog post](https://kentnek.com/geek/2020/07/yacht-yet-another-compilation-of-hugo-tricks/#theme-overrides-with-theme-components) about what I think is the best way to modify a theme (using theme components). You can give that a try!

**Comment by jakewies** [comment] 2020-07-15 13:41
@siberianTrousers any luck?

**Comment by siberianTrousers** [comment] 2020-07-15 18:36
Busy week, thanks for following up but will be the weekend before I can get to it again :) -- 
Statement of Confidentiality: 

The contents of this e-mail message and any attachments are        confidential and are intended solely for addressee. The        information may also be legally privileged. This transmission is        sent in trust, for the sole purpose of delivery to the intended        recipient. If you have received this transmission in error, any        use, reproduction or dissemination of this transmission is        strictly prohibited. If you are not the intended recipient, immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.



Jul 15, 2020, 09:42 by notifications@github.com:

**Comment by jakewies** [comment] 2020-07-17 02:38
No worries! I'm going to close this issue in the meantime as it should be fixed. Ping here if you have problems 😄

**Closed by jakewies** 2020-07-17 02:38 UTC
