### ISSUE TITLE
odd URL behavior, deployed to AWS Amplify

### ISSUE THREAD

**Issue by jwalsh2me** [jakewies/hugo-theme-codex#102] opened 2020-07-25 15:16 UTC
I am new to Hugo, just spun up a new site using Codex theme and build and deploy it via AWS Amplify.  I am seeing some off behavior in redirects and handling of pages.

Localhost works fine.  I was able to fix the blog posts by adding a trailing `/` to the url like:

```
[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog/"
```

That seemed to fix that and did not break running it local, but I noticed now when deployed that the category does not work because it is missing the trailing `/`

[hello-world](https://www.jwalsh2.me/blog/hello-world/)

[Python Tag](https://www.jwalsh2.me/tags/python/) works just fine, but the list of tags is created without the trailing `/` and lands to the home page `https://www.jwalsh2.me/tags/python`

I am trying to find which file to modify to add in the `/` to help this render.

Any help is appreciated!

Love the them, thanks for making it!

John

**Comment by jwalsh2me** [comment] 2020-07-26 14:38
OK, think it is an issue with Amplify and their default rewrite behavior. 

I added in two rules and the tags now work and I was able to remove the trailing `/` for `/blog`

<img width="1009" alt="Screen Shot 2020-07-26 at 9 32 28 AM" src="https://user-images.githubusercontent.com/22819585/88481880-93481080-cf23-11ea-8009-c0497b4c8444.png">

Had to make a few tweaks to make Amplify work with the theme, going to make a blog post on it.

**Comment by jwalsh2me** [comment] 2020-07-26 14:49
Actually, just pushed the problem somewhere else. 

So the #python tag works here now with the rewrite ->. https://www.jwalsh2.me/blog

But is broken here when clicking on the Python tag -> https://www.jwalsh2.me/blog/hello-world/

So I am back to the first issue...  Also seems similar to #103

**Comment by jwalsh2me** [comment] 2020-07-27 15:27
@jakewies any thoughts where I can look for the URL generation?

**Comment by jakewies** [comment] 2020-07-28 19:57
Hey @jwalsh2me , sorry that it has taken me some time to get to your issue. I could not reproduce the error outlined in your initial comment, but it looks like that issue was solved. Your new issue is that the tags on the post page are redirecting you to the home page.

There are some differences I'm noticing here:

1. The tags on the post-list page are not ending in a trailing slash. Clicking the tag redirects to the tag page (CORRECT)
2. The tags on the post page are ending in a trailing slash. Clicking the tag redirects to the home page (INCORRECT).

Now, this may be something to do with Amplify, and I don't have any experience with the platform. But we could try and figure out how to manipulate the trailing slash on our end, and see if the resolves the issue for you.

**Comment by jwalsh2me** [comment] 2020-07-29 01:15
Thanks let me dig into it some more.  It does seem like it is something Amplify is doing as the site demo page renders fine if I serve it up locally.

**Comment by jwalsh2me** [comment] 2020-07-31 15:35
@jakewies So I changed themes, went with Anatole.  No issues with the slashes.  Their config.toml does have all the trailing `/` for the pages.  I am not sure if there is just an inconsistency with the Codex theme in using / in some places or others.  But it works just fine serving up local, just other themes I do not seem to have to play with the config or add rewrites to the config.

AWS Amplify is to host on AWS, it basically abstracts a lot of the backend config for you so you do not need to manually setup CloudFront or S3.

**Comment by jakewies** [comment] 2020-10-18 15:58
This may have been solved in https://github.com/jakewies/hugo-theme-codex/pull/122. Closing.

**Closed by jakewies** 2020-10-18 15:58 UTC
